-- message.sql
-- 사용자 테이블 삭제 후 생성
DROP TABLE tbl_user CASCADE CONSTRAINTS PURGE;

CREATE TABLE tbl_user (
    uno	NUMBER 	GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    userid     VARCHAR2(50) NOT NULL UNIQUE,
    userpw     VARCHAR2(50) NOT NULL,
    username   VARCHAR2(50) NOT NULL,
    upoint  NUMBER DEFAULT 0
);

-----------------------------------------------------

-- 메시지 테이블 삭제 후 생성
DROP TABLE tbl_message CASCADE CONSTRAINTS;

CREATE TABLE tbl_message (
    mno       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- 메시지 번호
    targetid  VARCHAR2(50) NOT NULL,                 -- 수신자 아이디
    sender    VARCHAR2(50) NOT NULL,                 -- 발신자 아이디
    message   CLOB NOT NULL,                         -- 메시지 본문
    opendate  TIMESTAMP NULL,                        -- 수신 확인 시간
    senddate  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, -- 발신 시간
    CONSTRAINT fk_message_target FOREIGN KEY (targetid)
        REFERENCES tbl_user(userid),
    CONSTRAINT fk_message_sender FOREIGN KEY (sender)
        REFERENCES tbl_user(userid)
);


INSERT INTO tbl_user(userid, userpw, username) 
VALUES ('id001','pw001', 'IRON MAN');

INSERT INTO tbl_user(userid, userpw, username) 
VALUES ('id002','pw002', 'THOR');

INSERT INTO tbl_user(userid, userpw, username) 
VALUES ('id003','pw003', 'DR.strange');

SELECT * FROM tbl_user;

SELECT * FROM tbl_message ORDER BY mno DESC;

COMMIT


/*
	1 id001  pw001  IRON MAN       55
	2 id002  pw002  THOR           55
	3 id003  pw003  DR.strange    115
---------------------------------------------
	1 id001  pw001  IRON MAN       65
	2 id002  pw002  THOR           55
	3 id003  pw003  DR.strange    115
---------------------------------------------
    1 id001  pw001  IRON MAN       65
    2 id002  pw002  THOR           65
    3 id003  pw003  DR.strange    115
---------------------------------------------    
    1 id001  pw001  IRON MAN       65
    2 id002  pw002  THOR           65
    3 id003  pw003  DR.strange    115


 */








