
-- test_board 게시글의 댓글 저장용 테이블 생성
CREATE TABLE test_comment(
	cno			NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
	bno 		NUMBER NOT NULL, 								-- 댓글 부여 게시글 번호
	content 	CLOB NOT NULL,									-- 댓글 내용
	author		VARCHAR2(50) NOT NULL,							-- 댓글 작성자
	regdate		TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,		-- 작성 시간
	updatedate	TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,		-- 수정 시간
	CONSTRAINT fk_tbl_bno FOREIGN KEY(bno)
	REFERENCES test_board(bno) ON DELETE CASCADE
); 

DELETE FROM test_comment WHERE bno = 1;
DELETE FROM test_board WHERE bno = 1;

SELECT * FROM test_board ORDER BY bno DESC;

SELECT index_name, column_name, column_position
FROM user_ind_columns
WHERE table_name = 'TEST_COMMENT';

-- bno column index 부여 - 검색에 자주 사용
CREATE INDEX inx_test_comment_bno ON test_comment(bno);

-- test
SELECT * FROM test_board WHERE bno = 1;

INSERT INTO test_comment(bno, content, author)
VALUES(1, '피곤해', '김도은');

SELECT * FROM test_comment WHERE bno = 1 ORDER BY regdate DESC;

-- 페이징 처리 확인용 sample data 추가
INSERT INTO test_comment(bno, content, author)
SELECT bno, content, author FROM test_comment;

commit