DROP TABLE test_board PURGE;

-- 테스트용 게시판(board) 테이블
CREATE TABLE test_board(
	bno NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,	-- 글 번호
	title VARCHAR2(300) NOT NULL,										-- 제목
	content CLOB NOT NULL,												-- 내용
	writer VARCHAR2(50) NOT NULL,										-- 작성자
	regdate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,						-- 등록 시간
	viewcnt NUMBER DEFAULT 0											-- 조회수
);

SELECT * FROM test_board;

commit

INSERT INTO test_board(title, content, writer)
SELECT title, content, writer FROM test_board;