CREATE TABLE validation_user(
	u_no 			NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,		-- 회원 번호 자동 부여
	u_id 			VARCHAR2(200) NOT NULL UNIQUE,										-- 회원 아이디(이메일)
	u_pw 			VARCHAR2(50) NOT NULL,												-- 비밀번호
	u_name 			VARCHAR2(20) NOT NULL,												-- 이름
	u_phone 		VARCHAR2(20) NOT NULL,												-- 전화번호
	u_birth 		VARCHAR2(20) NOT NULL,												-- 생년월일
	u_addr 			VARCHAR2(200),														-- 주소		
	u_addr_detail 	VARCHAR2(100),														-- 상세 주소		
	u_addr_post 	VARCHAR2(10),														-- 우편번호
	u_point			NUMBER DEFAULT 0,													-- 포인트 점수
	u_info			char(1) DEFAULT 'y',												-- 개인 정보 이용 동의
	u_date			TIMESTAMP DEFAULT SYSTIMESTAMP,										-- 계정 생성일
	u_visit_date	TIMESTAMP DEFAULT SYSTIMESTAMP,										-- 최종 방문일
	u_withdraw		char(1) DEFAULT 'n'													-- 회원 탈퇴 여부
);

-- 프로필 이미지 경로를 문자열로 저장하는 column 추가
ALTER TABLE validation_user ADD u_profile VARCHAR2(300);

-- u_id, u_pw, u_name, u_phone, u_birth, u_addr, u_addr_detail, u_addr_post, u_profile

SELECT * FROM validation_user;